# Generated by Django 5.0.2 on 2024-02-26 16:41

import django.core.validators
import django.db.models.deletion
import init_service.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AvailableScreens",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("screen_json", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "Available Screen",
                "verbose_name_plural": "Available Screens",
                "db_table": "available_screens",
            },
        ),
        migrations.CreateModel(
            name="Role",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "role_name",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("admin", "Admin"),
                            ("cloud basic", "Cloud Basic"),
                            ("cloud manager", "Cloud Manager"),
                            ("cloud expert", "Cloud Expert"),
                        ],
                        max_length=255,
                        null=True,
                    ),
                ),
                ("role_status", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserScreens",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_screen", models.JSONField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "User Screen",
                "verbose_name_plural": "User Screens",
                "db_table": "user_screens",
            },
        ),
        migrations.CreateModel(
            name="AWSUser",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(blank=True, null=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "mobile",
                    models.CharField(
                        blank=True,
                        max_length=17,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Mobile number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                                regex="^\\+?\\d{9,15}$",
                            )
                        ],
                    ),
                ),
                ("login_status", models.BooleanField(default=False)),
                ("access_token", models.JSONField(blank=True, null=True)),
                ("refresh_token", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "role_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="init_service.role",
                    ),
                ),
            ],
            options={
                "verbose_name": "AWS User",
                "verbose_name_plural": "AWS Users",
                "db_table": "aws_user",
            },
        ),
        migrations.CreateModel(
            name="ProfilePicture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        default="default_profile_pic.jpg",
                        storage=init_service.models.MinioStorage(),
                        upload_to="",
                    ),
                ),
                (
                    "profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="init_service.awsuser",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="role",
            name="screens",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="init_service.userscreens",
            ),
        ),
    ]
