# Generated by Django 4.2 on 2024-03-10 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("init_service", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="role",
            name="role_name",
            field=models.CharField(
                blank=True,
                choices=[
                    ("admin", "Admin"),
                    ("cloud basic", "Cloud Basic"),
                    ("cloud manager", "Cloud Manager"),
                    ("cloud expert", "Cloud Expert"),
                    ("others", "Others"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
